dist: xenial
language: python
cache: pip

notifications:
  irc: "chat.freenode.net#pil"

# Run fast lint first to get fast feedback.
# Run slow PyPy next, to give it a headstart and reduce waiting time.
# Run latest 3.x next, to get quick compatibility results.
# Then run the remainder, with fastest Docker jobs last.

matrix:
  fast_finish: true
  include:
    - python: "3.8"
      arch: arm64
    - python: "3.8"
      arch: s390x

services:
  - docker

before_install:
  - if [ "$DOCKER" ]; then travis_retry docker pull pythonpillow/$DOCKER:$DOCKER_TAG; fi

install:
  - |
    if [ "$LINT" == "true" ]; then
      pip install tox
    elif [ "$DOCKER" == "" ]; then
      .travis/install.sh;
    fi

# AMD64 x86_64
# Arm64 aarch64
# ppc64le ppc64le
# s390x s390x
script:
- |
  python -c "import platform; print(platform.processor())"
  if [ "$LINT" == "true" ]; then
    tox -e lint
  elif [ "$DOCKER" == "" ]; then
    .travis/build.sh
    .travis/test.sh
  elif [ "$DOCKER" ]; then
    # the Pillow user in the docker container is UID 1000
    sudo chown -R 1000 $TRAVIS_BUILD_DIR
    docker run -v $TRAVIS_BUILD_DIR:/Pillow pythonpillow/$DOCKER:$DOCKER_TAG
  fi

after_success:
- |
  if [ "$LINT" == "" ]; then
    .travis/after_success.sh
  fi
