name: CIFuzz

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      id: build
      uses: radarhere/oss-fuzz/infra/cifuzz/actions/run_fuzzers@ci
      with:
        oss-fuzz-project-name: 'pillow'
        language: python
        dry-run: false
    - name: Run Fuzzers
      id: run
      uses: radarhere/oss-fuzz/infra/cifuzz/actions/run_fuzzers@ci
      with:
        oss-fuzz-project-name: 'pillow'
        fuzz-seconds: 600
        language: python
        dry-run: false
    - name: Upload New Crash
      uses: actions/upload-artifact@v4
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts
    - name: Upload Legacy Crash
      uses: actions/upload-artifact@v4
      if: steps.run.outcome == 'success'
      with:
        name: crash
        path: ./out/crash*
    - name: Fail on legacy crash
      if: success()
      run: |
        [ ! -e out/crash-* ]
        echo No legacy crash detected
