name: Docs

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  build:

    runs-on: ubuntu-latest
    name: Docs

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: pip
        cache-dependency-path: ".ci/*.sh"

    - name: Build system information
      run: python3 .github/workflows/system-info.py

    - name: Install Linux dependencies
      run: |
        .ci/install.sh
      env:
        GHA_PYTHON_VERSION: "3.x"

    - name: Build
      run: |
        .ci/build.sh

    - name: Docs
      run: |
        make doccheck
