name: Lint

on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: 1

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    name: Lint

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: pip
        cache-dependency-path: "setup.py"

    - name: Build system information
      run: python3 .github/workflows/system-info.py

    - name: Install dependencies
      run: |
        python3 -m pip install -U pip
        python3 -m pip install -U tox
        python3 -m pip install -U black
        python3 -m pip install ruff==0.5.6
        sudo apt-get -qq install hyperfine

    - name: Lint
      run: |
        git remote add akx https://github.com/akx/Pillow.git
        git fetch akx
        git checkout -b ruff-format-2024 akx/ruff-format-2024
        env BLACK_CACHE_DIR=/dev/null RUFF_NO_CACHE=true hyperfine --warmup 5 'git checkout 8291_test; make lint-fix' 'git checkout ruff-format-2024; make lint-fix'
