name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  COVERAGE_CORE: sysmon
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: ubuntu-latest
    name: Free
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y python3 jpeg-turbo tiff webp lcms2 freetype2 openjpeg harfbuzz fribidi libxcb

        run: |
          python3 -m ensurepip
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade Pillow --no-binary :all:
          python3 -m PIL

          python3 -m pip install pytest
          python3 -m pytest

