name: Test

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - ".github/workflows/docs.yml"
      - ".github/workflows/wheels*"
      - ".gitmodules"
      - "docs/**"
      - "wheels/**"
  pull_request:
    paths-ignore:
      - ".github/workflows/docs.yml"
      - ".github/workflows/wheels*"
      - ".gitmodules"
      - "docs/**"
      - "wheels/**"
  workflow_dispatch:

permissions:
  contents: read

env:
  COVERAGE_CORE: sysmon
  FORCE_COLOR: 1

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [
          "macos-latest",
        ]
        python-version: [
          "3.12",
        ]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python ${{ matrix.python-version }}
      uses: Quansight-Labs/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
        cache: pip
        cache-dependency-path: |
          ".ci/*.sh"
          "pyproject.toml"

    - name: Build system information
      run: python3 .github/workflows/system-info.py

    - name: Install macOS dependencies
      if: startsWith(matrix.os, 'macOS')
      run: |
        .github/workflows/macos-install.sh
      env:
        GHA_PYTHON_VERSION: ${{ matrix.python-version }}

    - name: Build
      run: |
        .ci/build.sh

    - name: Test
      run: |
        python3 demo.py
        python3 -m pip install --upgrade pip

        python3 -m pip install Pillow==11.0.0 -q --no-binary :all:
        python3 demo.py
        diff im-11.0.0.png im-11.2.0.dev0.png
        echo "11.0.0 from source matches 11.2.0.dev0 from source"

        python3 -m pip install Pillow==11.1.0 -q --no-binary :all:
        python3 demo.py
        diff im-11.1.0.png im-11.2.0.dev0.png
        echo "11.1.0 from source matches 11.2.0.dev0 from source"

        python3 -m pip install Pillow==11.0.0 -q
        python3 demo.py
        diff im-11.0.0.png im-11.2.0.dev0.png
        echo "11.0.0 wheel matches 11.2.0.dev0 from source"

        python3 -m pip install Pillow==11.1.0 -q
        python3 demo.py
        echo "And now, check 11.1.0 wheel against 11.2.0.dev0 from source"
        diff im-11.1.0.png im-11.2.0.dev0.png
        echo "11.1.0 wheel matches 11.2.0.dev0 from source"
