name: Test MSYS2

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  COVERAGE_CORE: sysmon

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # skip to save CI time:
          # see https://github.com/python-pillow/Pillow/pull/6888#issuecomment-1400392821
          # - msystem: "UCRT64"
          - msystem: "CLANG64"
    defaults:
      run:
        shell: bash.exe --login -eo pipefail "{0}"
    env:
      MSYSTEM: ${{ matrix.msystem }}
      CHERE_INVOKING: 1

    timeout-minutes: 30
    name: MSYS2 ${{ matrix.msystem }}

    steps:
      - name: Checkout Pillow
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up shell
        run: echo "C:\msys64\usr\bin\" >> $env:GITHUB_PATH
        shell: pwsh

      - name: Install dependencies
        run: |
          pacman -S --noconfirm \
              make \
              pactoys \
              subversion

          pacboy -S --noconfirm \
              gcc:p \
              python-pip:p

      - name: Build Pillow
        run: AR="ar" .ci/build.sh

      - name: Test Pillow
        run: .ci/test.sh

      - name: After success
        run: .ci/after_success.sh

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: GHA_Windows
          name: MSYS2 ${{ matrix.msystem }}
