name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  COVERAGE_CORE: sysmon
  FORCE_COLOR: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        std: [
          "-std=gnu17",
          "-std=gnu2x",
          "-std=gnu23",
        ]

    runs-on: ubuntu-latest
    name: Ghostscript with ${{ matrix.std }}

    steps:
    - name: Ghostscript
      run: |
        git clone https://github.com/ArtifexSoftware/ghostpdl
        cd ghostpdl
        export CFLAGS="${{ matrix.std }}"
        ./autogen.sh
        sudo make install
