name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  COVERAGE_CORE: sysmon
  FORCE_COLOR: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: "macos-14"

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install macOS dependencies
      run: |
        brew install python@3.12
        brew uninstall --ignore-dependencies freetype

    - name: Install FreeType
      run: |
        cd freetype-2.13.2
        export FT2_DEBUG="any:7"
        ./configure
        make
        sudo make install

    - name: Test
      run: |
        python3 -m pip install --break-system-packages .
        python3 demo.py
