name: Test

on:
  push:
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"
  pull_request:
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [
          "ubuntu-latest",
        ]
        python-version: [
          "pypy3.10",
          "pypy3.9",
          "3.12-dev",
          "3.11",
        ]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: ".ci/*.sh"

    - name: Build
      run: |
        export QT_DEBUG_PLUGINS=1
        sudo apt-get -qq install libegl1 libxcb-cursor0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 libxkbcommon-x11-0
        python3 -m pip install pyqt6
        xvfb-run -s '-screen 0 1024x768x24' .ci/test.sh
