name: Test

on:
  push:

permissions:
  contents: read

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [
          "macos-latest",
        ]
        python-version: [
          "3.8",
        ]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 1

    - name: Build system information
      run: |
        git tag
