name: Test

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - ".github/workflows/docs.yml"
      - ".github/workflows/wheels*"
      - ".gitmodules"
      - "docs/**"
      - "wheels/**"
  pull_request:
    paths-ignore:
      - ".github/workflows/docs.yml"
      - ".github/workflows/wheels*"
      - ".gitmodules"
      - "docs/**"
      - "wheels/**"
  workflow_dispatch:

permissions:
  contents: read

env:
  COVERAGE_CORE: sysmon
  FORCE_COLOR: 1

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [
          "macos-latest",
          "ubuntu-latest",
        ]
        python-version: [
          "pypy3.10",
          "3.13t",
          "3.13",
          "3.12",
          "3.11",
          "3.10",
          "3.9",
        ]
        include:
        - { python-version: "3.11", PYTHONOPTIMIZE: 1, REVERSE: "--reverse" }
        - { python-version: "3.10", PYTHONOPTIMIZE: 2 }
        # Free-threaded
        - { python-version: "3.13t", disable-gil: true }
        # M1 only available for 3.10+
        - { os: "macos-13", python-version: "3.9" }
        exclude:
        - { os: "macos-latest", python-version: "3.9" }

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python ${{ matrix.python-version }}
      uses: Quansight-Labs/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
        cache: pip
        cache-dependency-path: |
          ".ci/*.sh"
          "pyproject.toml"

    - name: Set PYTHON_GIL
      if: "${{ matrix.disable-gil }}"
      run: |
        echo "PYTHON_GIL=0" >> $GITHUB_ENV

    - name: Build system information
      run: python3 .github/workflows/system-info.py

    - name: Build
      run: |
        python3 -m pip install Pillow

    - name: Test
      run: |
        .ci/test.sh
