name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  COVERAGE_CORE: sysmon
  FORCE_COLOR: 1

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        version: [
          "master",
        ]

    runs-on: macos-latest
    name: ${{ matrix.version }}

    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: 3.13

    - name: Build system information
      run: python3 .github/workflows/system-info.py

    - name: Install
      run: |
        .github/workflows/macos-install.sh
      env:
        VERSION: ${{ matrix.version }}
