name: Test Docker

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker: [
          debian-9-stretch-x86,
        ]
        dockerTag: [master]

    name: ${{ matrix.docker }}

    steps:
    - uses: actions/checkout@v1

    - name: Build system information
      run: python .github/workflows/system-info.py

    - name: Docker pull
      run: |
        docker pull pythonpillow/${{ matrix.docker }}:${{ matrix.dockerTag }}

    - name: Prepare to upload errors
      run: |
        mkdir -p Tests/errors

    - name: Docker build
      run: |
        # The Pillow user in the docker container is UID 1000
        sudo chown -R 1000 $GITHUB_WORKSPACE
        sudo apt-get -y install curl
        docker run --name pillow_container  -v $GITHUB_WORKSPACE:/Pillow pythonpillow/${{ matrix.docker }}:${{ matrix.dockerTag }}
        #curl --upload-file ./out.jpg https://transfer.sh/out.jpg
        sudo chown -R runner $GITHUB_WORKSPACE

    - name: Upload errors
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: errors
        path: Tests/errors
