name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  COVERAGE_CORE: sysmon
  FORCE_COLOR: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        std: [
          "-std=gnu17",
          "-std=gnu23",
        ]

    runs-on: ubuntu-latest
    name: Ghostscript with ${{ matrix.std }}

    steps:
    - name: Ghostscript
      run: |
        wget https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs10051/ghostscript-10.05.1.tar.gz
        tar -xvzf ghostscript-10.05.1.tar.gz
        cd ghostscript-10.05.1 && CFLAGS="${{ matrix.std }}" ./configure --without-x
