name: Wheels

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  windows:
    name: Windows AMD64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Prepare for build
        run: |
          & python.exe winbuild\build_prepare.py -v --no-imagequant --architecture=AMD64
        shell: pwsh
