name: Wheels

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  windows:
    name: Windows AMD64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Prepare for build
        run: |
          git clone https://github.com/AOMediaCodec/libavif.git
          cmake -S libavif -B libavif/build -DAVIF_CODEC_RAV1E=LOCAL -DAVIF_LIBYUV=LOCAL
          cmake --build libavif/build --parallel
